### ISSUE TITLE
[FEAT] 최근 검색어

### ISSUE THREAD

**Issue by Ting97ok** [threethings3/threethings-server#15]
## 최근 검색어

> 최근 검색어 기록 및 조회

## 작업 상세 내용

- [ ] 최근 검색어 저장
- [ ] 최근 검색어 조회

## 참고 사항
https://www.figma.com/file/7bGGfuqprmHkTwAurasQ3V/%EC%93%B0%EB%A6%AC%EB%9D%B5%EC%A6%88-%EA%B8%B0%ED%9A%8D%EC%84%9C?type=design&node-id=424-3392&mode=design&t=medMIndJbZVvz1df-4

**Comment by devch96** [comment]
최근 검색어는 서버에서 저장하지 않는 것으로 결정.
